# Generated by Django 4.1.3 on 2022-11-03 04:32

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_code', models.UUIDField(unique=True, verbose_name='Секретный код')),
                ('confirm_code', models.CharField(max_length=128, verbose_name='Код подтверждения')),
                ('created_at', models.DateTimeField(verbose_name='Дата создания кода подтверждения')),
                ('confirmed', models.BooleanField(verbose_name='Подтвержден?')),
                ('type_confirm', models.CharField(choices=[('registration', 'Registration'), ('reset_pass', 'Reset Pass'), ('change', 'Change')], max_length=16, verbose_name='Тип')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Подтверждение email',
                'verbose_name_plural': 'Подтверждения emails',
            },
        ),
        migrations.CreateModel(
            name='ConfirmPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_code', models.UUIDField(unique=True, verbose_name='Секретный код')),
                ('confirm_code', models.CharField(max_length=128, verbose_name='Код подтверждения')),
                ('created_at', models.DateTimeField(verbose_name='Дата создания кода подтверждения')),
                ('confirmed', models.BooleanField(verbose_name='Подтвержден?')),
                ('type_confirm', models.CharField(choices=[('registration', 'Registration'), ('reset_pass', 'Reset Pass'), ('change', 'Change')], max_length=16, verbose_name='Тип')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Телефон')),
                ('count_send', models.PositiveIntegerField(default=1, verbose_name='Количество отправок')),
            ],
            options={
                'verbose_name': 'Подтверждение телефона',
                'verbose_name_plural': 'Подтверждения телефонов',
            },
        ),
    ]
